apiVersion: v1
kind: ServiceAccount
metadata:
  name: attestor-api-runtime
  annotations:
    iam.gke.io/gcp-service-account: attestor-runtime-sql@project-9180cbda-d681-42d8-8ca.iam.gserviceaccount.com
