apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: attestor-alertmanager-routing
  namespace: attestor-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: REPLACE_WITH_CLUSTER_SECRET_STORE
  target:
    name: attestor-alertmanager-routing
    creationPolicy: Owner
  data:
    - secretKey: ALERTMANAGER_DEFAULT_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: default_webhook_url
    - secretKey: ALERTMANAGER_CRITICAL_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: critical_webhook_url
    - secretKey: ALERTMANAGER_WARNING_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: warning_webhook_url
    - secretKey: ALERTMANAGER_DEFAULT_SLACK_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: default_slack_webhook_url
    - secretKey: ALERTMANAGER_DEFAULT_SLACK_CHANNEL
      remoteRef:
        key: observability/alertmanager
        property: default_slack_channel
    - secretKey: ALERTMANAGER_WARNING_SLACK_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: warning_slack_webhook_url
    - secretKey: ALERTMANAGER_WARNING_SLACK_CHANNEL
      remoteRef:
        key: observability/alertmanager
        property: warning_slack_channel
    - secretKey: ALERTMANAGER_CRITICAL_PAGERDUTY_ROUTING_KEY
      remoteRef:
        key: observability/alertmanager
        property: critical_pagerduty_routing_key
    - secretKey: ALERTMANAGER_SECURITY_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: security_webhook_url
    - secretKey: ALERTMANAGER_BILLING_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: billing_webhook_url
    - secretKey: ALERTMANAGER_EMAIL_TO
      remoteRef:
        key: observability/alertmanager
        property: email_to
    - secretKey: ALERTMANAGER_EMAIL_FROM
      remoteRef:
        key: observability/alertmanager
        property: email_from
    - secretKey: ALERTMANAGER_SMARTHOST
      remoteRef:
        key: observability/alertmanager
        property: smarthost
    - secretKey: ALERTMANAGER_SMTP_AUTH_USERNAME
      remoteRef:
        key: observability/alertmanager
        property: smtp_auth_username
    - secretKey: ALERTMANAGER_SMTP_AUTH_PASSWORD
      remoteRef:
        key: observability/alertmanager
        property: smtp_auth_password
    - secretKey: ALERTMANAGER_PRODUCTION_MODE
      remoteRef:
        key: observability/alertmanager
        property: production_mode
