apiVersion: v1
kind: Secret
metadata:
  name: attestor-otel-gateway-grafana-cloud
  namespace: attestor-observability
type: Opaque
stringData:
  grafana-cloud-otlp-endpoint: https://otlp-gateway-prod-us-east-2.grafana.net/otlp
  grafana-cloud-otlp-auth-header: Basic REPLACE_WITH_BASE64_USERNAME_COLON_TOKEN
