apiVersion: v1
kind: Secret
metadata:
  name: attestor-otel-gateway-grafana-cloud
  namespace: attestor-observability
type: Opaque
stringData:
  grafana-cloud-otlp-endpoint: https://otlp-gateway-prod-us-east-2.grafana.net/otlp
  grafana-cloud-otlp-username: REPLACE_WITH_GRAFANA_CLOUD_INSTANCE_ID
  grafana-cloud-otlp-token: REPLACE_WITH_GRAFANA_CLOUD_API_TOKEN
