apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: attestor-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: attestor-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis-url
      remoteRef:
        key: attestor/redis-url
    - secretKey: redis-address
      remoteRef:
        key: attestor/redis-address
    - secretKey: redis-password
      remoteRef:
        key: attestor/redis-password
    - secretKey: redis-username
      remoteRef:
        key: attestor/redis-username
    - secretKey: control-plane-pg-url
      remoteRef:
        key: attestor/control-plane-pg-url
    - secretKey: billing-ledger-pg-url
      remoteRef:
        key: attestor/billing-ledger-pg-url
    - secretKey: runtime-pg-url
      remoteRef:
        key: attestor/runtime-pg-url
    - secretKey: admin-api-key
      remoteRef:
        key: attestor/admin-api-key
    - secretKey: metrics-api-key
      remoteRef:
        key: attestor/metrics-api-key
