apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: attestor-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: attestor-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: attestor/tls-crt
    - secretKey: tls.key
      remoteRef:
        key: attestor/tls-key
