export {
  PROOF_SCENARIO_IDS,
  PROOF_SCENARIO_REGISTRY,
  PROOF_SURFACE_DECISIONS,
  PROOF_SURFACE_ENTRY_POINT_KINDS,
  PROOF_SURFACE_PACK_FAMILIES,
  PROOF_SURFACE_PROOF_MATERIAL_KINDS,
  PROOF_SURFACE_SPEC_VERSION,
  getProofScenario,
  listProofScenarioIds,
  proofScenarioRegistry,
  proofScenariosByPack,
  proofSurfaceDescriptor,
  type ProofScenarioCheckSet,
  type ProofScenarioConsequence,
  type ProofScenarioDefinition,
  type ProofScenarioEntryPoint,
  type ProofScenarioId,
  type ProofScenarioProofMaterial,
  type ProofSurfaceDecision,
  type ProofSurfaceDescriptor,
  type ProofSurfaceEntryPointKind,
  type ProofSurfacePackFamily,
  type ProofSurfaceProofMaterialKind,
} from './scenario-registry.js';
